# Template workflow file to use in repo we want to generate image.

name: Generate Mockup Screenshot Laptop
on:
  push:
    branches: [master]

jobs:
  generate-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: dispatch generator
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: screenshot-mockup-laptop-generator
          repo: myusf01/ss-pipe
          token: ${{ secrets.FLOW_TOKEN }}
          inputs: '{ "repo": "${{ github.repository }}" }'
